; Colors
COL_BLACK	.equ $00
COL_WHITE	.equ $01
COL_RED     .equ $02
COL_CYAN	.equ $03
COL_PURPLE	.equ $04
COL_GREEN	.equ $05
COL_BLUE	.equ $06
COL_YELLOW	.equ $07
COL_ORANGE	.equ $08
COL_BROWN	.equ $09
COL_PINK	.equ $0A
COL_DGREY	.equ $0B
COL_GREY	.equ $0C
COL_LGREEN	.equ $0D
COL_LBLUE	.equ $0E
COL_LGREY	.equ $0F

VIC_BASE .equ $d000

